name: Unzip Next.js Main File

on:
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Unzip the uploaded file
      - name: Unzip nextjs-main.zip
        run: |
          unzip nextjs-main.zip -d nextjs-main
          rm nextjs-main.zip
      
      # Step 3: Commit and push extracted files
      - name: Commit and Push Extracted Files
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Unzipped nextjs-main.zip"
          git push
