name: Unzip File

on:
  workflow_dispatch: # Trigger the workflow manually

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Unzip the file
      - name: Unzip the File
        run: |
          unzip nextjs-main.zip -d nextjs-main
          rm nextjs-main.zip

      # Commit the changes
      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Unzipped nextjs-main.zip"
          git push
